ORDER_PLACED = "Sipariş Alındı"

TRACKING_STATUS_NOT_PRESENT = "Henüz Kargoya Verilmedi"

SUPPORT_REQUEST_RECEIVED = "Talebiniz Alındı"

SIZE_VARIATION_TYPE = "Beden"

SKIP_SEARCH = "SKIP_SEARCH"
SKIP_CATEGORY = "SKIP_CATEGORY"
